// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
import type { About } from "./types";

export const about: About = {
  "missionEn": "We, the Center of Excellence of Communication Innovation for Development of Quality of Life and Sustainability at the Faculty of Communication Arts, Chulalongkorn University, are a research center dedicated to creating knowledge and developing communication innovations that enhance quality of life and sustainability.",
  "pillarsEn": [
    "Developing communication innovation for the improvement of quality of life and sustainability through teaching, learning, and training management.",
    "Coming together as a group or community to advocate for communication aimed at collectively developing the quality of life and sustainability within society.",
    "Developing innovative tools and equipment to help society understand and perceive the guidelines for developing quality of life and sustainability."
  ],
  "faculty": [
    {
      "slug": "smith",
      "name": "Assoc. Prof. Dr. Smith Boonchutima",
      "role": "Head of Research Operations Unit",
      "position": null,
      "education": [
        "Doctor of Philosophy in Sports Science, Chulalongkorn University, 2018",
        "The Global Media University of London, 2548",
        "Master of Arts in Mass Communication (Advertising), Chulalongkorn University, 2000",
        "Bachelor of Communication Arts (Advertising) (First-Class Honors), Chulalongkorn University, 2000"
      ]
    },
    {
      "slug": "teerada",
      "name": "Asst. Prof. Dr. Teerada (Ne) Chongkolrattanaporn",
      "role": "Deputy Head of Research Operations Unit",
      "position": "Assistant Professor in Public Relations Department, Faculty of Communication Arts, Chulalongkorn University (2009–present); Head of Department of Public Relations.",
      "education": [
        "Ph.D. International Communication, Macquarie University, Australia",
        "Ph.D. Communication Studies, Chulalongkorn University",
        "M.A. Speech and Communication Studies, San Francisco State University, USA",
        "B.A. English Language, Chulalongkorn University"
      ]
    },
    {
      "slug": "pavel",
      "name": "Assoc. Prof. Dr. Pavel Slutskiy",
      "role": "Faculty researcher · Department of Public Relations",
      "position": "Associate Professor, Department of Public Relations, Faculty of Communication Arts, Chulalongkorn University (2014–present). เกิดที่ Saint-Petersburg, Russia",
      "education": [
        "Ph.D. —"
      ],
      "_note": "Title pending confirmation from the center"
    }
  ],
  "widerTeam": [
    "Chanapa Itthiamornkulchai",
    "Ekasit Sumana",
    "Hrut Sitthipuwabun",
    "Pornpavee Thiuthipsakul",
    "Supatra Petchree",
    "Thavin Chaemchaeng",
    "Wanwisa Wetchprasit",
    "Wassayut Kongjan"
  ]
};

