// AUTO-GENERATED by scripts/build-content.mjs from content/posts/ — do not edit by hand.
// Lightweight post metadata (no body) — safe to import on every page.
import type { PostMeta } from "./types";
export const posts: readonly PostMeta[] = [
  {
    "slug": "asean-university-network",
    "title": "ASEAN University Network",
    "summary": "We designed and produced the ASEAN University Network annual report for 2016–2019, from concept and layout through to print-ready files.",
    "date": "2024-06-21",
    "tags": [
      "book-and-printing"
    ],
    "coverFilename": "25218b_2b0f2529e00142aaabbab10e2503df71-mv2.png",
    "ogDescription": "Comm.Inno designed and produced the ASEAN University Network annual report covering 2016–2019. We developed a creative, modern layout matched to the organisation's personality, supplied print-ready files to the printer, and prepared compressed versions for digital reading on the AUN website.",
    "coverImage": null
  },
  {
    "slug": "associate-professor-dr-smith-boonchutima-delivers-leadership-training-at-krungthai-bank",
    "title": "Associate Professor Dr. Smith Boonchutima Delivers Leadership Training at Krungthai Bank",
    "summary": "Assoc. Prof. Smith Boonchutima led \"The Art of Communication & Influencing\" for middle managers at Krungthai Bank, part of Sasin's Leadership Acceleration Program.",
    "date": "2025-07-23",
    "tags": [
      "training"
    ],
    "coverFilename": null,
    "coverAltEn": "Banking executives in a leadership training workshop",
    "coverAltTh": "ผู้บริหารธนาคารร่วมอบรมภาวะผู้นำ",
    "ogDescription": "On 23 July 2025, Assoc. Prof. Smith Boonchutima was keynote speaker for the Leadership Acceleration Program at Krungthai Bank, on the theme \"The Art of Communication & Influencing\". The day covered organisational communication, information management, word-of-mouth and rumour, presentation skills, conflict management and crisis communication, closing with digital public relations and hands-on practice using AI tools for news writing. The programme was organised by Sasin Graduate Institute of Business Administration.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/krungthai"
  },
  {
    "slug": "associate-professor-dr-smith-boonchutima-delivers-special-lecture-at-professional-treasury-officer",
    "title": "Associate Professor Dr. Smith Boonchutima Delivers Special Lecture at Professional Treasury Officer Program",
    "summary": "Assoc. Prof. Smith Boonchutima lectured 60 government executives on communication techniques for administration and public relations at the 15th Professional Treasury Officer Program.",
    "date": "2025-08-06",
    "tags": [
      "training"
    ],
    "coverFilename": null,
    "coverAltEn": "Speaker addressing executive treasury officers in a formal seminar setting",
    "coverAltTh": "วิทยากรบรรยายผู้บริหารสายการคลังในงานสัมมนาเชิงบริหาร",
    "ogDescription": "On 6 August 2025, Assoc. Prof. Smith Boonchutima delivered a special lecture on \"Communication Techniques for Administration and Public Relations\" at the 15th Professional Treasury Officer Program, organised by the Fiscal Policy Research Institute Foundation. The session covered communication strategy in government organisations, information management in the digital age, crisis communication, and the application of modern technology in public relations. Sixty government executives from a range of agencies attended.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/treasury"
  },
  {
    "slug": "center-of-excellence-head-invited-to-lead-executive-crisis-communication-training",
    "title": "Comm.Inno head invited to lead executive crisis communication training",
    "summary": "The head of Comm.Inno (Center of Excellence in Communication Innovation for the Development of Quality of Life and Sustainability) is invited to lead an executive crisis communication training programme.",
    "date": "2024-06-22",
    "tags": [
      "highlights",
      "school"
    ],
    "coverFilename": null,
    "coverAltEn": "Executive briefing in a crisis communication training session",
    "coverAltTh": "ห้องบรรยายสรุปสถานการณ์ในการอบรมการสื่อสารภาวะวิกฤตระดับผู้บริหาร",
    "ogDescription": "The head of Comm.Inno is invited to lead executive crisis communication training. One-day course equips C-suite leaders with vital skills for managing corporate image and personal conduct in crises.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/crisis-comm"
  },
  {
    "slug": "center-of-excellence-in-communication-innovation-launches-groundbreaking-online-course-for-digital-n",
    "title": "Comm.Inno launches groundbreaking online course for digital nomads",
    "summary": "Chula's Communication Arts launches online course for digital nomads in Thailand, starting Aug 1.",
    "date": "2024-06-19",
    "tags": [
      "highlights",
      "school"
    ],
    "coverFilename": "25218b_fc87e081e7bd4bdfa37bcab62e5a441c-mv2.jpg",
    "ogDescription": "Chula's Communication Arts launches online course for digital nomads in Thailand, starting Aug 1. Apply now at www.thesharpener.school",
    "coverImage": null
  },
  {
    "slug": "chula-communication-arts-strengthens-academic-collaboration-with-keio-university-and-bunkyo-universi",
    "title": "Chula Communication Arts Strengthens Academic Collaboration with Keio University and Bunkyo University",
    "summary": "A Chulalongkorn delegation visited Keio University and Bunkyo University in Tokyo to run a joint peace-communication workshop and open talks on exchanges and joint research.",
    "date": "2026-03-15",
    "tags": [
      "school"
    ],
    "coverFilename": null,
    "coverAltEn": "Delegation from Chulalongkorn University meeting Japanese academic partners in Tokyo",
    "coverAltTh": "คณะผู้แทนจุฬาลงกรณ์มหาวิทยาลัยพบปะพันธมิตรทางวิชาการญี่ปุ่น",
    "ogDescription": "In March 2026, faculty and students from Chulalongkorn's Department of Public Relations visited two leading Japanese institutions. At Keio University's Graduate School of Media Design, Asst. Prof. Teerada Chongkolrattanaporn led the workshop \"Peace Playground: A Workshop on Metaphor & Art\", with a lecture by Assoc. Prof. Shutaro Takeda. At Bunkyo University, faculty met Professor Masato Koizumi to discuss student exchanges, curriculum development and joint international research.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/chula-keio-bunkyo"
  },
  {
    "slug": "chula-zero-waste",
    "title": "Chula Zero Waste",
    "summary": "A student-led campaign prototype for cutting waste at Chulalongkorn University — built to be fun, bright, simple and practical.",
    "date": "2024-07-06",
    "tags": [
      "campaign-manage",
      "communication-design",
      "marketing-event"
    ],
    "coverFilename": "25218b_f9cc2a2218e0428bb5d13c02be940a08-mv2.jpg",
    "ogDescription": "Comm.Inno created a student-led campaign prototype for reducing waste at Chulalongkorn University, designed around four principles: fun, brightness, simplicity and practicality. It supports the Chula Zero Waste action plan for sustainable management of solid and hazardous waste (2017–2021), which set out to cut university waste by at least 30% through six programmes and eighteen projects, run with the Environmental Research Institute, the Office of Physical System Management and partner networks across the university.",
    "coverImage": null
  },
  {
    "slug": "comm-art-chula-ce-drives-national-drug-safety-awareness-at-fda-summit",
    "title": "Comm.Inno drives national drug safety awareness at FDA summit",
    "summary": "Comm.Inno brought an interactive rational-drug-use exhibition to Thailand's first National Forum on Rational Drug Use, with the FDA and ThaiHealth.",
    "date": "2025-07-09",
    "tags": [
      "innovation-technology"
    ],
    "coverFilename": null,
    "coverAltEn": "FDA national drug-safety summit exhibition booth and visitors",
    "coverAltTh": "บูธนิทรรศการประชุมระดับชาติเรื่องความปลอดภัยของอย.",
    "ogDescription": "Asst. Prof. Teerada Chongkolrattanaporn and Dr. Kamonrat Kijrungpaisarn worked with the Food and Drug Administration and the Thai Health Promotion Foundation to present the interactive exhibition \"กินยาสมเหตุ หายโรคสมผล ทุกคนสมใจ\" at Thailand's first National Forum on Rational Drug Use, held 8–9 July 2025 at Centara Life Government Complex, Bangkok. Healthcare professionals and the public took part through educational games and discussion of proper medication use. The exhibition is part of the center's research project on communication for medication use to reduce kidney-disease risk, funded by ThaiHealth.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/fda"
  },
  {
    "slug": "creative-tourism-development-project-in-nan-province",
    "title": "Creative Tourism Development Project in Nan Province",
    "summary": "We organized a workshop to enhance communication skills, starting with registration open to all interested residents of Nan.",
    "date": "2024-06-29",
    "tags": [
      "school",
      "seminar",
      "training"
    ],
    "coverFilename": "25218b_e7bd23371b4f4603b7d65d73bec679e6-mv2.jpg",
    "ogDescription": "We organized a workshop to enhance communication skills, starting with registration open to all interested residents of Nan. The event took place at the Namthong Nan Hotel, where we prepared photography and video equipment, decorative props, and lighting to help participants create more engaging images. The training included both theoretical and practical sessions, ensuring that all attendees gained valuable knowledge.",
    "coverImage": null
  },
  {
    "slug": "department-of-disease-control",
    "title": "Department of Disease Control",
    "summary": "Workshop on Service Process DesignThe discussion focused on principles of targeted communication and modern media production techniques.",
    "date": "2024-06-29",
    "tags": [
      "school",
      "seminar",
      "training"
    ],
    "coverFilename": "25218b_943a6e13b0094abc843b48445f4a0513-mv2.jpg",
    "ogDescription": "Workshop on Service Process DesignThe discussion focused on principles of targeted communication and modern media production techniques. These topics aimed to help participants build relationships and understanding within the organization, facilitate communication, and enhance the organization’s image.",
    "coverImage": null
  },
  {
    "slug": "dr-teerada-of-chulalongkorn-university-leads-workshop-preparing-thai-students-in-türkiye-for-the-wo",
    "title": "Dr. Teerada of Chulalongkorn University Leads Workshop Preparing Thai Students in Türkiye for the Workforce",
    "summary": "Asst. Prof. Teerada Chongkolrattanaporn led a two-day workshop in Istanbul preparing Thai students in Türkiye for the transition into professional work.",
    "date": "2025-07-05",
    "tags": [
      "training"
    ],
    "coverFilename": null,
    "coverAltEn": "Workshop participants and speaker in Istanbul preparing Thai students for the workforce",
    "coverAltTh": "ผู้เข้าร่วมปฏิบัติการในเวิร์กช็อปที่อิสตันบูลเตรียมความพร้อมสู่ตลาดแรงงานของนักศึกษาไทย",
    "ogDescription": "On 4–5 July 2025, Asst. Prof. Teerada Chongkolrattanaporn, Head of the Department of Public Relations, was the key speaker for \"Preparing Thai Students in Türkiye to the World of Work\" in Istanbul. Her sessions covered basic communication and negotiation techniques, resumé writing, self-introduction, and practical interview skills. The project was organised by the Royal Thai Embassy in Ankara and opened by H.E. Mr. Apirat Sugondhabhirom, Ambassador of Thailand to the Republic of Türkiye.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/turkiye"
  },
  {
    "slug": "empowering-youth-leaders",
    "title": "Empowering Youth Leaders",
    "summary": "A four-day workshop in Phatthalung equipping youth leaders and mentors from three southern provinces to design, run and evaluate their own well-being activities.",
    "date": "2024-04-28",
    "tags": [
      "seminar",
      "training",
      "highlights"
    ],
    "coverFilename": "25218b_40a013d83c714afbb81c7f935ea9ca38-mv2.jpg",
    "ogDescription": "The head of Comm.Inno's research unit facilitated a training workshop for youth leaders and mentors from three provinces in southern Thailand, held 10–13 November 2023 in Phatthalung and organised by Look South Peace. The workshop built participants' ability to plan, implement and evaluate activities promoting sexual, physical and mental well-being for young people, and to collaborate with other organisations.",
    "coverImage": null
  },
  {
    "slug": "international-labour-organization",
    "title": "International Labour Organization",
    "summary": "United Nations WorkshopOur team participated in the workshop to promote cooperation for sustainable development with the United Nations and its valuable agenda in Thailand.",
    "date": "2024-06-21",
    "tags": [
      "training",
      "seminar"
    ],
    "coverFilename": "25218b_2c64ead7cabf46dfb3907182edddcf0d-mv2.jpeg",
    "ogDescription": "United Nations WorkshopOur team participated in the workshop to promote cooperation for sustainable development with the United Nations and its valuable agenda in Thailand. We taught various techniques related to text usage, photography, videography, and the use of the TikTok application. These skills were aimed at producing high-quality work for presenting individual and group projects.",
    "coverImage": null
  },
  {
    "slug": "itd",
    "title": "ITD",
    "summary": "Expert roundtables on digital commerce, the global trade war, business and human rights, and Thai services trade — turned into a printed book.",
    "date": "2024-07-06",
    "tags": [
      "book-and-printing",
      "seminar",
      "research-and-evaluation"
    ],
    "coverFilename": "25218b_3fcbd73e5cd9485b99ddf5f70684b86d-mv2.jpg",
    "ogDescription": "Comm.Inno organised a series of meetings for ITD to gather expert opinion and analyse trends across four themes: digital commerce and the opportunity for Thai SMEs, the global trade war and the adaptation of Thailand's international trade sector, business and human rights, and the direction of Thailand's services trade in creating added value amid change. We also designed and printed a book as the tangible output of the discussions.",
    "coverImage": null
  },
  {
    "slug": "ministry-of-natural-resources-and-environment",
    "title": "Ministry of Natural Resources and Environment",
    "summary": "Personnel Development Training ProgramOur team conducted a training program for the staff of the Department of Environmental Quality Promotion, Ministry of Natural Resources and Environment.",
    "date": "2024-06-21",
    "tags": [
      "training",
      "seminar"
    ],
    "coverFilename": "25218b_96a67968827a4e05b8d1514670943484-mv2.jpeg",
    "ogDescription": "Personnel Development Training ProgramOur team conducted a training program for the staff of the Department of Environmental Quality Promotion, Ministry of Natural Resources and Environment. The training aimed to enhance their work efficiency by covering techniques for impactful writing and perfect photography. We also recommended equipment that would help elevate the professionalism of their work.",
    "coverImage": null
  },
  {
    "slug": "nbtc-encyclopedia",
    "title": "NBTC Encyclopedia",
    "summary": "An encyclopedia rebuilt for a younger readership — plain language, strong illustrations, and video for those who would rather listen.",
    "date": "2024-07-06",
    "tags": [
      "book-and-printing",
      "communication-design",
      "school"
    ],
    "coverFilename": "25218b_3400ec2582f248d4abc705149ac7365c-mv2.jpg",
    "ogDescription": "Comm.Inno produced an encyclopedia that gathers key topics, draws the connections between them, and explains them in language a younger generation reads easily. We began by gathering feedback from both younger and older readers to make sure the result would be widely read, then built a modern edition around engaging illustrations, with accompanying video for those who prefer to listen.",
    "coverImage": null
  },
  {
    "slug": "nia-100-faces",
    "title": "NIA 100 FACES",
    "summary": "We gathered 100 innovators (3 Years) who inspire creativity, presenting them through a website, Instagram, a book, and AR images.https://www.nia100faces.com/",
    "date": "2024-06-29",
    "tags": [
      "book-and-printing",
      "campaign-manage",
      "motion-effect-ar"
    ],
    "coverFilename": "25218b_4caad4d894fc4108b321da6753a27a44-mv2.png",
    "ogDescription": "We gathered 100 innovators (3 Years) who inspire creativity, presenting them through a website, Instagram, a book, and AR images.https://www.nia100faces.com/",
    "coverImage": null
  },
  {
    "slug": "nia-media-innovation",
    "title": "NIA Media Innovation",
    "summary": "Research into what \"media innovation\" actually means, launched with a full event production and a small projection-mapping display.",
    "date": "2024-06-29",
    "tags": [
      "video-production",
      "campaign-manage",
      "research-and-evaluation"
    ],
    "coverFilename": "25218b_537f83ece3da4ce7b69a402fd82c4319-mv2.jpg",
    "ogDescription": "Comm.Inno compiled research on the meaning of \"media innovation\" and produced the launch event end to end, handling preparations including lighting and sound and creating a small projection-mapping display. We also invited experts to give their perspective on media innovation in interviews during the event.",
    "coverImage": null
  },
  {
    "slug": "nia-satisfaction-survey-2020",
    "title": "NIA Satisfaction Survey 2020",
    "summary": "A mixed-methods customer satisfaction survey supporting service development at the National Innovation Agency.",
    "date": "2024-06-29",
    "tags": [
      "research-and-evaluation"
    ],
    "coverFilename": "25218b_70abf2b826a749fab8c5755b58ac9333-mv2.jpg",
    "ogDescription": "Comm.Inno supported the development of services at the National Innovation Agency (Public Organization) by conducting a customer satisfaction survey using mixed methods.",
    "coverImage": null
  },
  {
    "slug": "pid-thong-lang-phra-foundation",
    "title": "Pid Thong Lang Phra Foundation",
    "summary": "Continuing the royal initiativeOnline media production training Persuasion techniques and personality developmentTraining is organized by expert teachers in all 3 areas: 1.",
    "date": "2024-07-05",
    "tags": [
      "communication-design",
      "school",
      "seminar"
    ],
    "coverFilename": "25218b_0546265a29964393967ad1df973bc36b-mv2.jpg",
    "ogDescription": "Continuing the royal initiativeOnline media production training Persuasion techniques and personality developmentTraining is organized by expert teachers in all 3 areas: 1. Simple online media production. By using powerpoint Present work in progress to everyone. Creating power to drive society 2. Techniques for persuading listeners and 3. Teaching personality development to trainees from the Pid Thong Lang Phra Foundation as well.",
    "coverImage": null
  },
  {
    "slug": "seeds-for-cu-sustainability",
    "title": "Seeds for CU Sustainability",
    "summary": "Project presentation videos shot in Bangkok and the provinces, from pre-production through post, including aerial footage and stakeholder interviews.",
    "date": "2024-06-29",
    "tags": [],
    "coverFilename": "25218b_e8f088f77e1e471db8d8c9fabf27e5fd-mv2.png",
    "ogDescription": "Comm.Inno produced project presentation videos from pre-production through to post-production, with weekly meetings to gather client feedback at every stage. The finished films showcase the project's commitment to social sustainability, featuring aerial footage and interviews with the stakeholders involved.",
    "coverImage": null
  },
  {
    "slug": "sri-trang-agro-industry",
    "title": "Sri Trang Agro-Industry",
    "summary": "An online content-creation course for Sri Trang Agro-Industry employees, building in-house video and screen-recording skills for ongoing organisational learning.",
    "date": "2022-07-20",
    "tags": [
      "training"
    ],
    "coverFilename": null,
    "coverAltEn": "Corporate employees in an online-content creation workshop",
    "coverAltTh": "พนักงานบริษัทร่วมอบรมการผลิตคอนเทนต์ออนไลน์",
    "ogDescription": "Comm.Inno delivered a training course on online content creation for employees of Sri Trang Agro-Industry Public Company Limited, enabling them to produce video and screen-recorded material for ongoing organisational learning. The course was organised by the Sirindhorn Thai Language Institute, Chulalongkorn University, and held on 20–21 July 2022 at the Buri Sriphu Convention Center, Hat Yai.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/sri-trang"
  },
  {
    "slug": "thai-health-promotion-foundation-organises-simple-drug-communication-as-daily-routine-training-by",
    "title": "Thai Health Promotion Foundation organises 'Simple drug communication as daily routine' training by Comm.Inno",
    "summary": "Thai Health Promotion Foundation partners with Comm.Inno to deliver the 'Simple drug communication as daily routine' training for healthcare communicators.",
    "date": null,
    "tags": [
      "training",
      "campaign-manage"
    ],
    "coverFilename": null,
    "coverAltEn": "Pharmacist and patient discussing medication — simple drug communication training",
    "coverAltTh": "เภสัชกรอธิบายยาแบบเข้าใจง่ายให้ผู้ป่วย — อบรมสื่อสารยาแบบเข้าใจง่าย",
    "ogDescription": "Thai Health Promotion Foundation partners with Comm.Inno to deliver the 'Simple drug communication as daily routine' training for healthcare communicators.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/thpf-drug"
  },
  {
    "slug": "the-training-program-for-driving-public-and-social-communication-care-d-plus",
    "title": "The training program for driving public and social communication, Care D Plus.",
    "summary": "Chulalongkorn and the Ministry of Public Health launched Care D+, a national programme building compassionate communication between healthcare staff, patients and families.",
    "date": "2024-04-28",
    "tags": [
      "marketing-event",
      "video-production",
      "campaign-manage"
    ],
    "coverFilename": null,
    "coverAltEn": "Healthcare workers in a Care D+ communication training programme",
    "coverAltTh": "บุคลากรสาธารณสุขร่วมอบรมหลักสูตร Care D+ ด้านการสื่อสาร",
    "ogDescription": "Chulalongkorn University, in collaboration with the Ministry of Public Health, launched the Care D+ training programme for driving public and social communication. It answers a Ministry priority designated a 100-day Quick Win: more than 90% of conflicts and complaints in the health system arise from communication breakdowns or inadequate crisis communication. The Care D Plus team — the \"Heartfelt Team\" — works in every healthcare unit to build empathy, understanding and mutual respect between patients, relatives and healthcare personnel, with Chulalongkorn providing the communication training.",
    "coverImage": "https://res.cloudinary.com/dpzdw1bkr/image/upload/f_auto,q_auto/comminno/insights/care-d-plus"
  }
] as const;
export const postsBySlug = new Map<string, PostMeta>(
  posts.map((p) => [p.slug, p])
);
