// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
import type { Redirect } from "./types";

export const redirects: readonly Redirect[] = [
  {
    "from": "/about/teerada-ne",
    "to": "/about#teerada"
  },
  {
    "from": "/blank",
    "to": "/about#smith"
  },
  {
    "from": "/insights/categories/book-printing",
    "to": "/services/book-and-printing"
  },
  {
    "from": "/insights/categories/campaign-manage",
    "to": "/services/campaign-manage"
  },
  {
    "from": "/insights/categories/communication-design",
    "to": "/services/communication-design"
  },
  {
    "from": "/insights/categories/highlights",
    "to": "/insights?category=highlights"
  },
  {
    "from": "/insights/categories/innovation-technology",
    "to": "/insights?category=innovation-technology"
  },
  {
    "from": "/insights/categories/marketing-event",
    "to": "/services/marketing-event"
  },
  {
    "from": "/insights/categories/motion-effect-ar",
    "to": "/services/motion-effect-ar"
  },
  {
    "from": "/insights/categories/research-evaluation",
    "to": "/services/research-and-evaluation"
  },
  {
    "from": "/insights/categories/school",
    "to": "/insights?category=school"
  },
  {
    "from": "/insights/categories/seminar",
    "to": "/services/seminar"
  },
  {
    "from": "/insights/categories/training",
    "to": "/services/training"
  },
  {
    "from": "/insights/categories/video-production",
    "to": "/services/video-production"
  },
  {
    "from": "/post/__itd",
    "to": "/insights/itd"
  },
  {
    "from": "/post/asean-university-network",
    "to": "/insights/asean-university-network"
  },
  {
    "from": "/post/associate-professor-dr-smith-boonchotima-delivers-leadership-training-at-krungthai-bank",
    "to": "/insights/associate-professor-dr-smith-boonchutima-delivers-leadership-training-at-krungthai-bank"
  },
  {
    "from": "/post/associate-professor-dr-smith-boonchutima-delivers-special-lecture-at-professional-treasury-officer",
    "to": "/insights/associate-professor-dr-smith-boonchutima-delivers-special-lecture-at-professional-treasury-officer"
  },
  {
    "from": "/post/center-of-excellence-head-invited-to-lead-executive-crisis-communication-training",
    "to": "/insights/center-of-excellence-head-invited-to-lead-executive-crisis-communication-training"
  },
  {
    "from": "/post/center-of-excellence-in-communication-innovation-launches-groundbreaking-online-course-for-digital-n",
    "to": "/insights/center-of-excellence-in-communication-innovation-launches-groundbreaking-online-course-for-digital-n"
  },
  {
    "from": "/post/chula-communication-arts-strengthens-academic-collaboration-with-keio-university-and-bunkyo-universi",
    "to": "/insights/chula-communication-arts-strengthens-academic-collaboration-with-keio-university-and-bunkyo-universi"
  },
  {
    "from": "/post/chula-zero-waste",
    "to": "/insights/chula-zero-waste"
  },
  {
    "from": "/post/comm-art-chula-ce-drives-national-drug-safety-awareness-at-fda-summit",
    "to": "/insights/comm-art-chula-ce-drives-national-drug-safety-awareness-at-fda-summit"
  },
  {
    "from": "/post/creative-tourism-development-project-in-nan-province",
    "to": "/insights/creative-tourism-development-project-in-nan-province"
  },
  {
    "from": "/post/department-of-disease-control",
    "to": "/insights/department-of-disease-control"
  },
  {
    "from": "/post/dr-teerada-of-chulalongkorn-university-leads-workshop-preparing-thai-students-in-t%C3%BCrkiye-for-the-wo",
    "to": "/insights/dr-teerada-of-chulalongkorn-university-leads-workshop-preparing-thai-students-in-t%C3%BCrkiye-for-the-wo"
  },
  {
    "from": "/post/empowering-youth-leaders",
    "to": "/insights/empowering-youth-leaders"
  },
  {
    "from": "/post/international-labour-organization",
    "to": "/insights/international-labour-organization"
  },
  {
    "from": "/post/ministry-of-natural-resources-and-environment",
    "to": "/insights/ministry-of-natural-resources-and-environment"
  },
  {
    "from": "/post/nbtc-encyclopedia",
    "to": "/insights/nbtc-encyclopedia"
  },
  {
    "from": "/post/nia-100-faces",
    "to": "/insights/nia-100-faces"
  },
  {
    "from": "/post/nia-media-innovation",
    "to": "/insights/nia-media-innovation"
  },
  {
    "from": "/post/nia-satisfaction-survey-2020",
    "to": "/insights/nia-satisfaction-survey-2020"
  },
  {
    "from": "/post/pid-thong-lang-phra-foundation",
    "to": "/insights/pid-thong-lang-phra-foundation"
  },
  {
    "from": "/post/seeds-for-cu-sustainability",
    "to": "/insights/seeds-for-cu-sustainability"
  },
  {
    "from": "/post/sri-trang-agro-industry",
    "to": "/insights/sri-trang-agro-industry"
  },
  {
    "from": "/post/thai-health-promotion-foundation-organises-simple-drug-communication-as-daily-routine-training-by",
    "to": "/insights/thai-health-promotion-foundation-organises-simple-drug-communication-as-daily-routine-training-by"
  },
  {
    "from": "/post/the-training-program-for-driving-public-and-social-communication-care-d-plus",
    "to": "/insights/the-training-program-for-driving-public-and-social-communication-care-d-plus"
  },
  {
    "from": "/privacy-policy",
    "to": "/privacy"
  }
] as const;

