// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
//
// Canonical body copy (descriptionEn/Th, deliverables*, audience*) will be
// spliced in by scripts/splice-services-copy.mjs once services_copy.md
// arrives in /home/ubuntu/projects/comminno-a8270f37/.
//
import type { Service } from "./types";

export const services: readonly Service[] = [
  {
    "slug": "book-and-printing",
    "titleEn": "Book & Printing",
    "titleTh": "หนังสือและสิ่งพิมพ์",
    "sdgNumber": 4,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "campaign-manage",
    "titleEn": "Campaign Manage",
    "titleTh": "บริหารแคมเปญ",
    "sdgNumber": 17,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "communication-design",
    "titleEn": "Communication Design",
    "titleTh": "ออกแบบการสื่อสาร",
    "sdgNumber": 9,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "marketing-event",
    "titleEn": "Marketing Event",
    "titleTh": "อีเวนต์การตลาด",
    "sdgNumber": 8,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "motion-effect-ar",
    "titleEn": "Motion Effect & AR",
    "titleTh": "Motion Effect และ AR",
    "sdgNumber": 9,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "research-and-evaluation",
    "titleEn": "Research & Evaluation",
    "titleTh": "วิจัยและประเมินผล",
    "sdgNumber": 4,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "seminar",
    "titleEn": "Seminar",
    "titleTh": "สัมมนา",
    "sdgNumber": 4,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "training",
    "titleEn": "Training",
    "titleTh": "ฝึกอบรม",
    "sdgNumber": 4,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  },
  {
    "slug": "video-production",
    "titleEn": "Video Production",
    "titleTh": "งานวิดีโอ",
    "sdgNumber": 16,
    "descriptionEn": null,
    "descriptionTh": null,
    "deliverablesEn": null,
    "deliverablesTh": null,
    "audienceEn": null,
    "audienceTh": null
  }
] as const;

export const servicesBySlug = new Map<string, Service>(
  services.map((s) => [s.slug, s])
);

