// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.

export type Locale = "th" | "en";

/** Post metadata (no body) — safe to import on every page. */
export interface PostMeta {
  slug: string;
  title: string;
  summary: string;
  /** ISO date YYYY-MM-DD, or null if source was missing it. */
  date: string | null;
  /** Category slugs from the original Wix taxonomy. */
  tags: string[];
  /** Original Wix-side image filename (binaries arrive in comminno_images.zip). */
  coverFilename: string | null;
  /** Long-form OG description from the original site, sentence-cased. */
  ogDescription: string;
}

/** Full post = metadata + body. Import only on InsightDetail. */
export interface Post extends PostMeta {
  body: string;
}

export interface Category {
  slug: string;
  titleEn: string;
  titleTh: string | null;
  isService: boolean;
}

export interface Service {
  slug: string;
  titleEn: string;
  titleTh: string | null;
  /** UN SDG goal number (1-17) — matches --sdg-{n} in tokens.css. */
  sdgNumber: number | null;
  /** Canonical body copy — null until services_copy.md is spliced in. */
  descriptionEn: string | null;
  descriptionTh: string | null;
  deliverablesEn: string[] | null;
  deliverablesTh: string[] | null;
  audienceEn: string | null;
  audienceTh: string | null;
}

export interface FacultyMember {
  slug: string;
  name: string;
  role: string;
  position: string | null;
  education: string[];
  _note?: string;
}

export interface About {
  missionEn: string;
  pillarsEn: string[];
  faculty: FacultyMember[];
  widerTeam: string[];
}

export interface Redirect {
  /** Wix path (e.g. "/post/chula-zero-waste"). */
  from: string;
  /** New path (e.g. "/insights/chula-zero-waste"). */
  to: string;
}

